# Generated by Django 3.2 on 2021-05-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210501_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
